spring:
    application:
        name: AllInServer
    exposed:
        generate-ddl: true
        show-sql: true
#    sql:
#        init:
#            schema-locations:
#                - classpath:db.sql
#            platform: postgresql
    profiles:
        active: dev