spring:
    application:
        name: AllInServer
    threads:
        virtual:
            enabled: true
#    sql:
#        init:
#            schema-locations:
#                - classpath:db.sql
#            platform: postgresql
    profiles:
        active: dev

jimmer:
    language: kotlin
    default-enum-strategy: ORDINAL
    dialect: org.babyfish.jimmer.sql.dialect.PostgresDialect
    show-sql: true
    pretty-sql: true
    database-validation:
        mode: error
