spring:
    application:
        name: AllInServer
    threads:
        virtual:
            enabled: true
#    sql:
#        init:
#            schema-locations:
#                - classpath:db.sql
#            platform: postgresql
    profiles:
        active: prod
    main:
        web-application-type: reactive

jimmer:
    language: kotlin
    default-enum-strategy: ORDINAL
    dialect: org.babyfish.jimmer.sql.dialect.PostgresDialect
    show-sql: true
    pretty-sql: true
    database-validation-mode: error
#    client:
#        openapi:
#            path: /openapi.yml
#            ui-path: /openapi.html
#            properties:
#              info:
#                  title: 项目api文档

logging:
    level:
      org.springframework.boot.autoconfigure: error
