[versions]
android-compileSdk = "34"
android-minSdk = "26"
android-targetSdk = "34"
android-gradle = "8.5.2"

#https://github.com/JetBrains/kotlin
kotlin = "2.0.21"
#https://github.com/JetBrains/kotlin-wrappers
kotlin-wrappers = "1.0.0-pre.839"
#https://github.com/Kotlin/kotlinx.coroutines
kotlinx-coroutines = "1.9.0"
#https://github.com/Kotlin/kotlinx.serialization
kotlinx-serialization = "1.7.3"
#https://github.com/Kotlin/kotlinx-datetime
kotlinx-datetime = "0.6.1"
#https://github.com/Kotlin/kotlinx-io
kotlinx-io = "0.5.4"
#https://github.com/google/ksp
ksp = "2.0.21-1.0.28"
#https://github.com/square/kotlinpoet
kotlinpoet = "2.0.0"
#https://github.com/Kotlin/kotlinx.collections.immutable
kotlinx-collections-immutable = "0.3.7"
#https://github.com/JetBrains/compose-multiplatform
jetbrains-compose = "1.7.1"
jetbrains-md3Adaptive = "1.0.0"
#https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/androidx/lifecycle/lifecycle-viewmodel-compose/
jetbrains-lifecycle = "2.8.4"
#https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/androidx/navigation/navigation-common/
jetbrains-navigation = "2.8.0-alpha10"
#https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/androidx/core/core-bundle/
jetbrains-core-bundle = "1.0.1"
#https://github.com/square/okhttp
okhttp3 = "4.12.0"
#https://github.com/ktorio/ktor
ktor = "3.0.1"
#https://github.com/square/okio
okio = "3.9.0"
#https://github.com/coil-kt/coil
coil3 = "3.0.4"
#https://github.com/InsertKoinIO/koin
koin = "4.0.0"
#https://github.com/InsertKoinIO/koin-annotations
koin-annotations = "1.4.0"
#https://github.com/oleksandrbalan/lazytable
lazytable = "1.9.0-beta01"

spring-boot = "3.4.0"
spring-dependencyManagement = "1.1.6"
#https://github.com/turansky/seskar
seskar = "3.60.0"
#https://github.com/babyfish-ct/jimmer
jimmer = "0.9.21"

activity = "1.9.3"
paging = "3.3.4"

slf4j = "2.0.13"
#https://github.com/jwtk/jjwt
jjwt = "0.12.6"
#https://github.com/ben-manes/caffeine
caffeine = "3.1.8"
#https://github.com/Guardsquare/proguard
proguard = "7.6.0"

junit = "4.13.2"


[plugins]

ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
android-application = { id = "com.android.application", version.ref = "android-gradle" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
kotlin-composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
spring = { id = "org.springframework.boot", version.ref = "spring-boot" }
srpingDependencyManagement = { id = "io.spring.dependency-management", version.ref = "spring-dependencyManagement" }
seskar = { id = "io.github.turansky.seskar", version.ref = "seskar" }

[libraries]
kotlin-gradle = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-reactor = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-reactor", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-serialization-protobuf = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-protobuf", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
kotlinx-io-bytestring = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-bytestring", version.ref = "kotlinx-io" }
kotlinx-io-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-core", version.ref = "kotlinx-io" }

kotlin-wrappers-bom = { module = "org.jetbrains.kotlin-wrappers:kotlin-wrappers-bom", version.ref = "kotlin-wrappers" }
kotlin-wrappers-emotion = { module = "org.jetbrains.kotlin-wrappers:kotlin-emotion" }
kotlin-wrappers-react = { module = "org.jetbrains.kotlin-wrappers:kotlin-react" }
kotlin-wrappers-react-dom = { module = "org.jetbrains.kotlin-wrappers:kotlin-react-dom" }
kotlin-wrappers-react-router = { module = "org.jetbrains.kotlin-wrappers:kotlin-react-router" }
kotlin-wrappers-react-router-dom = { module = "org.jetbrains.kotlin-wrappers:kotlin-react-router-dom" }
kotlin-wrappers-mui-material = { module = "org.jetbrains.kotlin-wrappers:kotlin-mui-material" }
kotlin-wrappers-mui-datePickers = { module = "org.jetbrains.kotlin-wrappers:kotlin-mui-date-pickers" }
kotlin-wrappers-mui-icons = { module = "org.jetbrains.kotlin-wrappers:kotlin-mui-icons-material" }

ksp = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
ksp-aa = { group = "com.google.devtools.ksp", name = "symbol-processing-aa", version.ref = "ksp" }


jetbrains-adaptive-navigation = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive-navigation", version.ref = "jetbrains-md3Adaptive" }
jetbrains-adaptive-suite = { group = "org.jetbrains.compose.material3", name = "material3-adaptive-navigation-suite", version.ref = "jetbrains-md3Adaptive" }
jetbrains-collection = { group = "org.jetbrains.compose.collection-internal", name = "collection", version.ref = "jetbrains-compose" }
jetbrains-navigation-compose = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "jetbrains-navigation" }
jetbrains-navigation-runtime = { group = "org.jetbrains.androidx.navigation", name = "navigation-runtime", version.ref = "jetbrains-navigation" }
jetbrains-lifecycle-viewmodelCompose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "jetbrains-lifecycle" }
jetbrains-lifecycle-vmSavedState = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "jetbrains-lifecycle" }
jetbrains-core-bundle = { group = "org.jetbrains.androidx.core", name = "core-bundle", version.ref = "jetbrains-core-bundle" }

kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }
kotlinpoet-jvm = { module = "com.squareup:kotlinpoet-jvm", version.ref = "kotlinpoet" }
squareup-okhttp3-okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp3" }
squareup-okhttp3-loggingInterceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3" }

reactor-test = { module = "io.projectreactor:reactor-test" }
junit-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }

koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-core-coroutines = { group = "io.insert-koin", name = "koin-core-coroutines", version.ref = "koin" }
koin-androidx-workmanager = { group = "io.insert-koin", name = "koin-androidx-workmanager", version.ref = "koin" }
koin-androidx-compose-navigation = { group = "io.insert-koin", name = "koin-androidx-compose-navigation", version.ref = "koin" }
koin-test = { group = "io.insert-koin", name = "koin-test", version.ref = "koin" }
koin-kmp-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel", version.ref = "koin" }
koin-annotations = { group = "io.insert-koin", name = "koin-annotations", version.ref = "koin-annotations" }
koin-compiler = { group = "io.insert-koin", name = "koin-ksp-compiler", version.ref = "koin-annotations" }
lazytable = { module = "io.github.oleksandrbalan:lazytable", version.ref = "lazytable" }

coil3-bom = { module = "io.coil-kt.coil3:coil-bom", version.ref = "coil3" }
coil3-core = { module = "io.coil-kt.coil3:coil-core" }
coil3-compose = { module = "io.coil-kt.coil3:coil-compose" }
coil3-gif = { module = "io.coil-kt.coil3:coil-gif" }
coil3-svg = { module = "io.coil-kt.coil3:coil-svg" }
coil3-video = { module = "io.coil-kt.coil3:coil-video" }
coil3-network-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3" }
coil3-network-core = { module = "io.coil-kt.coil3:coil-network-core" }
coil3-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp" }


ktorClient-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktorClient-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktorClient-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktorClient-serialization-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktorClient-resources = { group = "io.ktor", name = "ktor-client-resources", version.ref = "ktor" }
ktorClient-websockets = { group = "io.ktor", name = "ktor-client-websockets", version.ref = "ktor" }
ktorClient-java = { group = "io.ktor", name = "ktor-client-java", version.ref = "ktor" }
ktorClient-js = { group = "io.ktor", name = "ktor-client-js", version.ref = "ktor" }
ktorClient-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktorClient-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktorClient-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }


spring-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-starter-cache = { module = "org.springframework.boot:spring-boot-starter-cache" }
spring-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-starter-oauth2-resourceServer = { module = "org.springframework.boot:spring-boot-starter-oauth2-resource-server" }
spring-securityTest = { module = "org.springframework.security:spring-security-test" }
spring-starter-dataJdbc = { module = "org.springframework.boot:spring-boot-starter-data-jdbc" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }
spring-devtools = { module = "org.springframework.boot:spring-boot-devtools" }
spring-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-session-core = { module = "org.springframework.session:spring-session-core" }
spring-integration-mqtt = { module = "org.springframework.integration:spring-integration-mqtt" }
spring-integration-ip = { module = "org.springframework.integration:spring-integration-ip" }

postgresql = { module = "org.postgresql:postgresql" }

jimmer-spring = { module = "org.babyfish.jimmer:jimmer-spring-boot-starter", version.ref = "jimmer" }
jimmer-ksp = { module = "org.babyfish.jimmer:jimmer-ksp", version.ref = "jimmer" }


android-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-gradle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
androidx-paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging" }
androidx-paging-common = { group = "androidx.paging", name = "paging-common", version.ref = "paging" }

slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }
jjwt = { module = "io.jsonwebtoken:jjwt", version.ref = "jjwt" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

[bundles]
netLibs = [
    "squareup-okhttp3-okhttp",
    "squareup-okhttp3-loggingInterceptor"
]

commonKtorClient = [
    "ktorClient-core",
    "ktorClient-content-negotiation",
    "ktorClient-logging",
    "ktorClient-serialization-json",
    "ktorClient-websockets",
]