services:
  pgsql:
    build:
      context: .
      dockerfile: zh_pgsql.dockerfile
    container_name: my-pg
    environment:
      #      POSTGRES_USER: allkt
      POSTGRES_PASSWORD: 1234
      LANG: zh_CN.UTF-8
      LANGUAGE: zh_CN:en_US
      LC_ALL: zh_CN.UTF-8
      TZ: Asia/Shanghai
    ports:
      - "5432:5432"
    volumes:
      - data-db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: my-redis
    environment:
      LANG: zh_CN.UTF-8
      LANGUAGE: zh_CN:en_US
      LC_ALL: zh_CN.UTF-8
    ports:
      - "6379:6379"
    command: [ "redis-server","--requirepass","qwerdf" ]

  aws:
    image: minio/minio:latest
    container_name: my-aws
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 1234
    volumes:
      - data-aws:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: [ "server","/data","--console-address",":9001" ]


  #内网穿透
  frpService:
    image: ghcr.io/fatedier/frps:v0.62.1
    container_name: frpService
    environment:
      TZ: Asia/Shanghai
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
    volumes:
      - /home/frp/frpService.toml:/etc/frp/frps.toml
    command: -c /etc/frp/frps.toml

  nginx:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - "80:80"
    depends_on:
      - frpService
    volumes:
      - /home/nginx/conf.d:/etc/nginx/conf.d
      - /home/nginx/html:/usr/share/nginx/html

volumes:
  data-db:

  data-aws:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/data/aws
